# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 272614a8d720eb603724860352a71e3b3b9603c651dbdbc78d9423e3cd8beae6bdc37667d54249920a3d47362122b45c05edcfa60d2b63509485a149e231401f

test:
  secret_key_base: a7481a8949921723a61dc2ab360da9ed440a7ba30d6166d35c45f6d7b7b4af18e3033fc13b5907986f1350ff9e4f247dbaf0cccf1d83c9d872a24a4fbc911d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
